
name: npm-publish

on:
  push:
    branches:
      - main
jobs:
 build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 12.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: yarn install
      - name: Package release archive
        run: yarn run package
      - name: Save release archive
        uses: actions/upload-artifact@v2
        with:
          name: release-archive-${{ matrix.os }}
          path: build/*.zip

 release-npm:
   runs-on: ubuntu-latest
   needs: build
   steps:
      - name: Download Files For Adding To The Release Assets
        uses: actions/download-artifact@v2
      - name: View Downloaded Content
        run: ls -R
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'release-archive-*/*.zip'
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }




